const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "aarav@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Update Website Banner",
        taskDescription: "Design and upload the new homepage banner.",
        taskDate: "2026-05-25",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Fix Login Bug",
        taskDescription: "Resolve login authentication issue.",
        taskDate: "2026-05-20",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: false,
        taskTitle: "Prepare Sales Report",
        taskDescription: "Create monthly sales analytics report.",
        taskDate: "2026-05-28",
        category: "Analytics",
      },
    ],
  },

  {
    id: 2,
    firstName: "Vihaan",
    email: "vihaan@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 1,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Client Meeting",
        taskDescription: "Attend project discussion with client.",
        taskDate: "2026-05-26",
        category: "Management",
      },
      {
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Database Backup",
        taskDescription: "Backup production database securely.",
        taskDate: "2026-05-18",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        taskTitle: "API Integration",
        taskDescription: "Integrate payment gateway API.",
        taskDate: "2026-05-19",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: false,
        taskTitle: "Write Documentation",
        taskDescription: "Document authentication module.",
        taskDate: "2026-05-30",
        category: "Documentation",
      },
    ],
  },

  {
    id: 3,
    firstName: "Ishaan",
    email: "ishaan@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Create UI Components",
        taskDescription: "Build reusable React UI components.",
        taskDate: "2026-05-27",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Optimize Images",
        taskDescription: "Compress website images for faster loading.",
        taskDate: "2026-05-21",
        category: "Optimization",
      },
      {
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: false,
        taskTitle: "SEO Audit",
        taskDescription: "Review website SEO performance.",
        taskDate: "2026-05-29",
        category: "Marketing",
      },
    ],
  },

  {
    id: 4,
    firstName: "Aditya",
    email: "aditya@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 1,
    },
    tasks: [
      {
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Test Payment System",
        taskDescription: "Run QA tests on payment module.",
        taskDate: "2026-05-17",
        category: "Testing",
      },
      {
        active: false,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Deploy Staging Build",
        taskDescription: "Deploy latest version to staging server.",
        taskDate: "2026-05-24",
        category: "Deployment",
      },
      {
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        taskTitle: "Fix CSS Issues",
        taskDescription: "Resolve responsive layout problems.",
        taskDate: "2026-05-22",
        category: "Frontend",
      },
      {
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: false,
        taskTitle: "Security Audit",
        taskDescription: "Check application vulnerabilities.",
        taskDate: "2026-06-01",
        category: "Security",
      },
    ],
  },

  {
    id: 5,
    firstName: "Krishna",
    email: "krishna@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 1,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completedTask: false,
        failedTask: false,
        taskTitle: "Research Competitors",
        taskDescription: "Analyze competitor product features.",
        taskDate: "2026-05-31",
        category: "Research",
      },
      {
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        taskTitle: "Email Campaign",
        taskDescription: "Send marketing emails to subscribers.",
        taskDate: "2026-05-15",
        category: "Marketing",
      },
      {
        active: true,
        newTask: false,
        completedTask: false,
        failedTask: false,
        taskTitle: "Prepare Presentation",
        taskDescription: "Create slides for team meeting.",
        taskDate: "2026-05-27",
        category: "Presentation",
      },
      {
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        taskTitle: "Server Maintenance",
        taskDescription: "Update server packages and restart services.",
        taskDate: "2026-05-16",
        category: "DevOps",
      },
    ],
  },
];
const admin = [
  {
    id: 100,
    firstName: "Harsh",
    email: "Harsh@me.com",
    password: "123",
  },
];

export const setLocalStorageData = () => {
  const employeedata = localStorage.setItem(
    "employees",
    JSON.stringify(employees),
  );
  const admindata = localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorageData = () => {
  const employeesData = JSON.parse(localStorage.getItem("employees"));
  const adminData = JSON.parse(localStorage.getItem("admin"));
  return { employees: employeesData, admin: adminData };
};
